// swift-tools-version: 6.2

import PackageDescription

let package = Package(
    name: "MacApp",
    platforms: [.macOS(.v15)],
    products: [
        .library(name: "MacApp", targets: ["MacApp"]),
    ],
    dependencies: [
        .package(path: "../AppUpdate"),
        .package(path: "../DesignSystem"),
        .package(path: "../ExportFeature"),
        .package(path: "../HomeFeature"),
        .package(path: "../Media"),
        .package(path: "../PlayerFeature"),
        .package(path: "../Project"),
        .package(path: "../ProjectPreparation"),
        .package(path: "../ProjectSession"),
        .package(path: "../ProjectFeature"),
        .package(path: "../Settings"),
        .package(path: "../SettingsFeature"),
        .package(path: "../ShortsFeature"),
        .package(path: "../SpeakerAnalysis"),
        .package(path: "../SpeechToText"),
        .package(path: "../Subtitles"),
        .package(path: "../SubtitleEditorFeature"),
        .package(path: "../Timeline"),
        .package(path: "../TimelineFeature"),
        .package(path: "../TranscriptionPipeline"),
        .package(path: "../Translation"),
        .package(path: "../TranslationPipeline"),
        .package(path: "../VideoExport"),
        .package(path: "../VideoRendering"),
    ],
    targets: [
        .target(
            name: "MacApp",
            dependencies: [
                .product(name: "AppUpdate", package: "AppUpdate"),
                .product(name: "AppUpdateImpl", package: "AppUpdate"),
                .product(name: "DesignSystem", package: "DesignSystem"),
                .product(name: "ExportFeature", package: "ExportFeature"),
                .product(name: "ExportFeatureImpl", package: "ExportFeature"),
                .product(name: "HomeFeature", package: "HomeFeature"),
                .product(name: "HomeFeatureImpl", package: "HomeFeature"),
                .product(name: "Media", package: "Media"),
                .product(name: "MediaImpl", package: "Media"),
                .product(name: "PlayerFeature", package: "PlayerFeature"),
                .product(name: "PlayerFeatureImpl", package: "PlayerFeature"),
                .product(name: "Project", package: "Project"),
                .product(name: "ProjectImpl", package: "Project"),
                .product(name: "ProjectPreparation", package: "ProjectPreparation"),
                .product(name: "ProjectPreparationImpl", package: "ProjectPreparation"),
                .product(name: "ProjectSession", package: "ProjectSession"),
                .product(name: "ProjectSessionImpl", package: "ProjectSession"),
                .product(name: "ProjectFeature", package: "ProjectFeature"),
                .product(name: "ProjectFeatureImpl", package: "ProjectFeature"),
                .product(name: "Settings", package: "Settings"),
                .product(name: "SettingsImpl", package: "Settings"),
                .product(name: "SettingsFeatureImpl", package: "SettingsFeature"),
                .product(name: "ShortsFeature", package: "ShortsFeature"),
                .product(name: "ShortsFeatureImpl", package: "ShortsFeature"),
                .product(name: "SpeakerAnalysis", package: "SpeakerAnalysis"),
                .product(name: "SpeakerAnalysisImpl", package: "SpeakerAnalysis"),
                .product(name: "SpeechToText", package: "SpeechToText"),
                .product(name: "SpeechToTextImpl", package: "SpeechToText"),
                .product(name: "Subtitles", package: "Subtitles"),
                .product(name: "SubtitlesImpl", package: "Subtitles"),
                .product(name: "SubtitleEditorFeature", package: "SubtitleEditorFeature"),
                .product(name: "SubtitleEditorFeatureImpl", package: "SubtitleEditorFeature"),
                .product(name: "Timeline", package: "Timeline"),
                .product(name: "TimelineImpl", package: "Timeline"),
                .product(name: "TimelineFeature", package: "TimelineFeature"),
                .product(name: "TimelineFeatureImpl", package: "TimelineFeature"),
                .product(name: "TranscriptionPipeline", package: "TranscriptionPipeline"),
                .product(name: "TranscriptionPipelineImpl", package: "TranscriptionPipeline"),
                .product(name: "TranslationImpl", package: "Translation"),
                .product(name: "TranslationPipeline", package: "TranslationPipeline"),
                .product(name: "TranslationPipelineImpl", package: "TranslationPipeline"),
                .product(name: "VideoExport", package: "VideoExport"),
                .product(name: "VideoExportImpl", package: "VideoExport"),
                .product(name: "VideoRendering", package: "VideoRendering"),
                .product(name: "VideoRenderingImpl", package: "VideoRendering"),
            ],
            path: "Sources"
        ),
        .testTarget(
            name: "MacAppTests",
            dependencies: [
                "MacApp",
                .product(name: "ExportFeature", package: "ExportFeature"),
                .product(name: "PlayerFeature", package: "PlayerFeature"),
                .product(name: "Project", package: "Project"),
                .product(name: "ProjectFeature", package: "ProjectFeature"),
                .product(name: "ProjectSession", package: "ProjectSession"),
                .product(name: "ProjectSessionImpl", package: "ProjectSession"),
                .product(name: "ShortsFeature", package: "ShortsFeature"),
                .product(name: "Subtitles", package: "Subtitles"),
                .product(name: "SubtitleEditorFeature", package: "SubtitleEditorFeature"),
                .product(name: "TimelineFeature", package: "TimelineFeature"),
                .product(name: "VideoExport", package: "VideoExport"),
                .product(name: "VideoRendering", package: "VideoRendering"),
            ],
            path: "Tests/MacAppTests"
        ),
    ],
    swiftLanguageModes: [.v5]
)
